apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-test-api
  labels:
    app: devops-test-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-test-api
  template:
    metadata:
      labels:
        app: devops-test-api
    spec:
      containers:
      - name: devops-test-api
        image: apatora/devops-test-api:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
        env:
          - name: REDIS_HOST
            value: redis
          - name: REDIS_PORT
            value: 6379
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redisecret
          - name: MONGO_HOST
            value: mongodb
          - name: MONGO_PORT
            value: 27017
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongosecret
                key: username
          - name: MONGO_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: mongosecret
                key: password